#!/usr/bin/env python

Import("env")
Import("env_modules")

# Only kept to build the thirdparty library used by the theora and webm
# modules.

env_orbital2d = env_modules.Clone()

# Godot source files
env_orbital2d.add_source_files(env.modules_sources, "*.cpp")